from .. import BaseServer as BaseServer, Plugin as Plugin
from ..errors import ExtensionAlreadyLoaded as ExtensionAlreadyLoaded, ExtensionNotFound as ExtensionNotFound, NoEntryPointError as NoEntryPointError
from ..utils import MISSING as MISSING
from .__base import BasePlugin as BasePlugin
from _typeshed import Incomplete

log: Incomplete

class BasePlugin_Commands(BasePlugin, description='指令處理'):
    async def on_command_plugin_list(self) -> None: ...
    async def on_command_plugin_remove(self, name: str = ...): ...
    async def on_command_plugin_add(self, name: str = ...): ...
    async def on_command_plugin_reload(self, name: str = ...): ...
    async def on_command_send_all(self, message: str = ...): ...

def setup(server: BaseServer): ...
