from .. import BaseServer as BaseServer, Context as Context, Plugin as Plugin
from .__base import BasePlugin as BasePlugin
from _typeshed import Incomplete

log: Incomplete

class BasePlugin_Events(BasePlugin, description='事件日誌'):
    async def on_connect(self, ctx: Context): ...
    async def on_message(self, ctx: Context, msg: str): ...
    async def on_disconnect(self, ctx: Context): ...

def setup(server: BaseServer) -> None: ...
