from typing import Any, Optional

class ChatBridgeEError(Exception): ...

class ExtensionError(ChatBridgeEError):
    def __init__(self, msg: Optional[str] = None, *args: Any) -> None: ...

class ExtensionNotFound(ExtensionError):
    def __init__(self, name: str) -> None: ...

class NoEntryPointError(ExtensionError):
    def __init__(self, name: str) -> None: ...

class ExtensionAlreadyLoaded(ExtensionError):
    def __init__(self, name: str) -> None: ...
