name: releaser
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .github/**
      - .vscode/**
      - "!.github/workflows/**"
  # schedule:
  #   - cron: 33 17 * * *
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v4

      - name: Clone
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: __old_version
          ref: releaser

      - name: releaser
        run: |
          git config --global user.name "$user_name"
          git config --global user.email "$user_email"

          rsync -a extra/ __old_version/
          cd __old_version

          git add -A
          if [[ `git status --porcelain` ]]; then
            git commit -m "Update release files"
            git push -f https://_:"$token"@$repository "$ref_name":"$ref_name"
          fi
        shell: bash
        env:
          repository: github.com/${{ github.repository }}
          ref_name: releaser
          token: ${{ secrets.GITHUB_TOKEN }}
          user_name: GitHub Action
          user_email: action@github.com
