name: releaser
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/**
      - .vscode/**
      - "!.github/workflows/**"
  # schedule:
  #   - cron: 33 17 * * *
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v3

      - name: releaser
        run: |
          git config --global user.name "$user_name"
          git config --global user.email "$user_email"
          git init
          git add -f discord
          git commit -m "${{ github.event.head_commit.message }}"
          git push -f https://_:"$token"@github.com/"$repository".git "$ref_name":assets
        shell: bash
        env:
          repository: ${{ github.repository }}
          ref_name: master
          token: ${{ secrets.GITHUB_TOKEN }}
          user_name: GitHub Action
          user_email: action@github.com
          cname: none
